<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ScheduleInformationTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('schedule_information')->delete();

        \DB::table('schedule_information')->insert(array (
            0 => 
            array (
                'id' => 1,
                'title' => 'PRC Inspection @ Chemlab for CATO Renewal',
                'information' => NULL,
                'venue' => 'DOST IX RSTL (CHEMLAB)',
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => NULL,
                'conforme_id' => NULL,
                'schedule_id' => 1,
                'created_at' => '2026-06-15 10:38:40',
                'updated_at' => '2026-06-15 10:38:40',
            ),
            1 => 
            array (
                'id' => 2,
                'title' => NULL,
                'information' => 'Road Tanker (6,000 L) - Steve Maravilla (09177104453)',
                'venue' => NULL,
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => 93,
                'conforme_id' => NULL,
                'schedule_id' => 2,
                'created_at' => '2026-06-15 13:19:11',
                'updated_at' => '2026-06-15 13:19:11',
            ),
            2 => 
            array (
                'id' => 3,
                'title' => 'On-Site Deployment',
                'information' => 'To provide training on NAWI and Test Measures.',
                'venue' => 'Pagadian City',
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => NULL,
                'conforme_id' => NULL,
                'schedule_id' => 3,
                'created_at' => '2026-06-15 13:20:35',
                'updated_at' => '2026-06-15 13:20:35',
            ),
            3 => 
            array (
                'id' => 5,
                'title' => NULL,
                'information' => 'To render Calibration services to Baker\'s Field',
                'venue' => NULL,
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => 1560,
                'conforme_id' => NULL,
                'schedule_id' => 5,
                'created_at' => '2026-06-15 13:21:43',
                'updated_at' => '2026-06-15 13:21:43',
            ),
            4 => 
            array (
                'id' => 6,
                'title' => NULL,
                'information' => '20,000 kL',
                'venue' => NULL,
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => 194,
                'conforme_id' => 954,
                'schedule_id' => 6,
                'created_at' => '2026-06-15 13:22:53',
                'updated_at' => '2026-06-15 13:22:53',
            ),
            5 => 
            array (
                'id' => 7,
                'title' => 'WQMA Meeting',
                'information' => 'Governing Board Meeting',
                'venue' => 'La Casa Maria',
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => NULL,
                'conforme_id' => NULL,
                'schedule_id' => 7,
                'created_at' => '2026-06-15 13:23:53',
                'updated_at' => '2026-06-15 13:23:53',
            ),
            6 => 
            array (
                'id' => 8,
                'title' => NULL,
                'information' => '-',
                'venue' => NULL,
                'samples' => 4,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => 90,
                'conforme_id' => 275,
                'schedule_id' => 8,
                'created_at' => '2026-06-15 13:24:55',
                'updated_at' => '2026-06-15 13:24:55',
            ),
            7 => 
            array (
                'id' => 9,
                'title' => NULL,
                'information' => '20 KL',
                'venue' => NULL,
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => 15,
                'conforme_id' => 76,
                'schedule_id' => 9,
                'created_at' => '2026-06-15 13:25:39',
                'updated_at' => '2026-06-15 13:25:39',
            ),
            8 => 
            array (
                'id' => 10,
                'title' => NULL,
                'information' => 'Ipil Zamboanga Sibugay and Lower Irasan, Zamboanga del Norte',
                'venue' => NULL,
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => 1568,
                'conforme_id' => NULL,
                'schedule_id' => 10,
                'created_at' => '2026-06-15 13:28:16',
                'updated_at' => '2026-06-15 13:28:16',
            ),
            9 => 
            array (
                'id' => 11,
                'title' => 'Training Pressure Metrology',
                'information' => 'Calibration of Pressure gauge',
                'venue' => 'DOST-ITDI',
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => NULL,
                'conforme_id' => NULL,
                'schedule_id' => 11,
                'created_at' => '2026-06-15 13:29:26',
                'updated_at' => '2026-06-15 13:29:26',
            ),
            10 => 
            array (
                'id' => 12,
                'title' => 'Independence Day',
                'information' => NULL,
                'venue' => NULL,
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => NULL,
                'conforme_id' => NULL,
                'schedule_id' => 12,
                'created_at' => '2026-06-15 13:29:55',
                'updated_at' => '2026-06-15 13:29:55',
            ),
            11 => 
            array (
                'id' => 13,
                'title' => 'Amun Jadid (Islamic New Year)',
                'information' => NULL,
                'venue' => NULL,
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => NULL,
                'conforme_id' => NULL,
                'schedule_id' => 13,
                'created_at' => '2026-06-15 13:30:15',
                'updated_at' => '2026-06-15 13:30:15',
            ),
            12 => 
            array (
                'id' => 14,
                'title' => NULL,
                'information' => '20 kL - 0917 773 0173',
                'venue' => NULL,
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => 15,
                'conforme_id' => NULL,
                'schedule_id' => 14,
                'created_at' => '2026-06-15 13:33:25',
                'updated_at' => '2026-06-15 13:33:25',
            ),
            13 => 
            array (
                'id' => 16,
                'title' => NULL,
                'information' => '6,000 L',
                'venue' => NULL,
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => 1636,
                'conforme_id' => 1240,
                'schedule_id' => 16,
                'created_at' => '2026-06-15 13:34:45',
                'updated_at' => '2026-06-15 13:34:45',
            ),
            14 => 
            array (
                'id' => 17,
                'title' => NULL,
                'information' => '6,000 L',
                'venue' => NULL,
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => 1636,
                'conforme_id' => 1240,
                'schedule_id' => 17,
                'created_at' => '2026-06-15 13:35:21',
                'updated_at' => '2026-06-15 13:35:21',
            ),
            15 => 
            array (
                'id' => 18,
                'title' => NULL,
                'information' => 'Wellness Leave',
                'venue' => NULL,
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => NULL,
                'conforme_id' => NULL,
                'schedule_id' => 18,
                'created_at' => '2026-06-15 13:37:08',
                'updated_at' => '2026-06-15 13:37:08',
            ),
            16 => 
            array (
                'id' => 19,
                'title' => NULL,
                'information' => 'Personal',
                'venue' => NULL,
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => NULL,
                'conforme_id' => NULL,
                'schedule_id' => 19,
                'created_at' => '2026-06-15 13:37:31',
                'updated_at' => '2026-06-15 13:37:31',
            ),
            17 => 
            array (
                'id' => 20,
                'title' => NULL,
                'information' => '24,000 L',
                'venue' => NULL,
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => 37,
                'conforme_id' => NULL,
                'schedule_id' => 20,
                'created_at' => '2026-06-15 13:38:04',
                'updated_at' => '2026-06-15 13:38:04',
            ),
            18 => 
            array (
                'id' => 21,
                'title' => NULL,
                'information' => '20,000 L',
                'venue' => NULL,
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => 37,
                'conforme_id' => NULL,
                'schedule_id' => 21,
                'created_at' => '2026-06-15 13:38:28',
                'updated_at' => '2026-06-15 13:38:28',
            ),
            19 => 
            array (
                'id' => 22,
                'title' => NULL,
                'information' => '14,000 L',
                'venue' => NULL,
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => 37,
                'conforme_id' => NULL,
                'schedule_id' => 22,
                'created_at' => '2026-06-15 13:39:20',
                'updated_at' => '2026-06-15 13:39:20',
            ),
            20 => 
            array (
                'id' => 23,
                'title' => NULL,
                'information' => 'TSR # R9-062025-MET-0355',
                'venue' => NULL,
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => 996,
                'conforme_id' => 1250,
                'schedule_id' => 23,
                'created_at' => '2026-06-15 13:40:11',
                'updated_at' => '2026-06-15 13:40:11',
            ),
            21 => 
            array (
                'id' => 24,
                'title' => NULL,
                'information' => '20 kL - 0917 773 0173',
                'venue' => NULL,
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => 15,
                'conforme_id' => NULL,
                'schedule_id' => 24,
                'created_at' => '2026-06-15 13:40:41',
                'updated_at' => '2026-06-15 13:40:41',
            ),
            22 => 
            array (
                'id' => 25,
                'title' => NULL,
                'information' => '#48, Chico, Baliwasan, Zamboanga City',
                'venue' => NULL,
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => 4261,
                'customer_id' => 1639,
                'conforme_id' => NULL,
                'schedule_id' => 25,
                'created_at' => '2026-06-15 13:41:45',
                'updated_at' => '2026-06-15 13:41:45',
            ),
            23 => 
            array (
                'id' => 27,
                'title' => NULL,
                'information' => '1 unit 24 kL Road Tanker; Edward Bacuna (09536640502)',
                'venue' => NULL,
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => 1025,
                'conforme_id' => 695,
                'schedule_id' => 27,
                'created_at' => '2026-06-15 13:43:13',
                'updated_at' => '2026-06-15 13:43:13',
            ),
            24 => 
            array (
                'id' => 29,
                'title' => NULL,
                'information' => '20,000 L, Contact Person: Luther Gonzales - 09561859676',
                'venue' => NULL,
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => 57,
                'conforme_id' => NULL,
                'schedule_id' => 29,
                'created_at' => '2026-06-15 13:44:37',
                'updated_at' => '2026-06-15 13:44:37',
            ),
            25 => 
            array (
                'id' => 30,
                'title' => NULL,
                'information' => '-',
                'venue' => NULL,
                'samples' => 5,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => 90,
                'conforme_id' => NULL,
                'schedule_id' => 30,
                'created_at' => '2026-06-15 13:45:12',
                'updated_at' => '2026-06-15 13:45:12',
            ),
            26 => 
            array (
                'id' => 34,
                'title' => 'Ninoy Aquino Day',
                'information' => NULL,
                'venue' => NULL,
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => NULL,
                'conforme_id' => NULL,
                'schedule_id' => 34,
                'created_at' => '2026-06-15 13:47:30',
                'updated_at' => '2026-06-15 13:47:30',
            ),
            27 => 
            array (
                'id' => 35,
                'title' => 'National Heroes Day',
                'information' => NULL,
                'venue' => NULL,
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => NULL,
                'conforme_id' => NULL,
                'schedule_id' => 35,
                'created_at' => '2026-06-15 13:47:50',
                'updated_at' => '2026-06-15 13:47:50',
            ),
            28 => 
            array (
                'id' => 41,
                'title' => 'Fiesta Pilar',
                'information' => NULL,
                'venue' => NULL,
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => NULL,
                'conforme_id' => NULL,
                'schedule_id' => 41,
                'created_at' => '2026-06-15 13:50:55',
                'updated_at' => '2026-06-15 13:50:55',
            ),
            29 => 
            array (
                'id' => 42,
                'title' => 'All Saints\' Day',
                'information' => NULL,
                'venue' => NULL,
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => NULL,
                'conforme_id' => NULL,
                'schedule_id' => 42,
                'created_at' => '2026-06-15 13:51:39',
                'updated_at' => '2026-06-15 13:51:39',
            ),
            30 => 
            array (
                'id' => 43,
                'title' => 'All Souls\' Day',
                'information' => NULL,
                'venue' => NULL,
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => NULL,
                'conforme_id' => NULL,
                'schedule_id' => 43,
                'created_at' => '2026-06-15 13:53:52',
                'updated_at' => '2026-06-15 13:53:52',
            ),
            31 => 
            array (
                'id' => 44,
                'title' => 'Feast of the Immaculate Conception of Mary',
                'information' => NULL,
                'venue' => NULL,
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => NULL,
                'conforme_id' => NULL,
                'schedule_id' => 44,
                'created_at' => '2026-06-15 13:54:30',
                'updated_at' => '2026-06-15 13:54:30',
            ),
            32 => 
            array (
                'id' => 45,
                'title' => 'Christmas Eve',
                'information' => NULL,
                'venue' => NULL,
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => NULL,
                'conforme_id' => NULL,
                'schedule_id' => 45,
                'created_at' => '2026-06-15 13:54:50',
                'updated_at' => '2026-06-15 13:54:50',
            ),
            33 => 
            array (
                'id' => 46,
                'title' => 'Christmas Day',
                'information' => NULL,
                'venue' => NULL,
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => NULL,
                'conforme_id' => NULL,
                'schedule_id' => 46,
                'created_at' => '2026-06-15 13:55:13',
                'updated_at' => '2026-06-15 13:55:13',
            ),
            34 => 
            array (
                'id' => 47,
                'title' => 'Rizal Day',
                'information' => NULL,
                'venue' => NULL,
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => NULL,
                'conforme_id' => NULL,
                'schedule_id' => 47,
                'created_at' => '2026-06-15 13:55:33',
                'updated_at' => '2026-06-15 13:55:33',
            ),
            35 => 
            array (
                'id' => 48,
                'title' => 'Last Year of the Day',
                'information' => NULL,
                'venue' => NULL,
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => NULL,
                'conforme_id' => NULL,
                'schedule_id' => 48,
                'created_at' => '2026-06-15 13:55:50',
                'updated_at' => '2026-06-15 13:55:50',
            ),
            36 => 
            array (
                'id' => 49,
                'title' => 'Anthony A. Javier',
                'information' => 'Personal Leave',
                'venue' => NULL,
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => NULL,
                'conforme_id' => NULL,
                'schedule_id' => 49,
                'created_at' => '2026-06-15 15:16:45',
                'updated_at' => '2026-08-06 07:16:10',
            ),
            37 => 
            array (
                'id' => 50,
                'title' => NULL,
                'information' => 'ZCEZA I, SMB-6, San Ramon, Talisayan, Zamboanga City',
                'venue' => NULL,
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => 3982,
                'customer_id' => 1501,
                'conforme_id' => NULL,
                'schedule_id' => 50,
                'created_at' => '2026-06-15 15:21:21',
                'updated_at' => '2026-06-15 15:21:21',
            ),
            38 => 
            array (
                'id' => 51,
                'title' => '2nd Quarter GAD General Assembly',
                'information' => NULL,
                'venue' => NULL,
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => NULL,
                'conforme_id' => NULL,
                'schedule_id' => 51,
                'created_at' => '2026-06-17 11:43:28',
                'updated_at' => '2026-06-17 11:43:28',
            ),
            39 => 
            array (
                'id' => 52,
                'title' => NULL,
                'information' => 'Either 20,000 L or 18,000 L',
                'venue' => NULL,
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => 37,
                'conforme_id' => NULL,
                'schedule_id' => 52,
                'created_at' => '2026-06-17 14:04:44',
                'updated_at' => '2026-06-17 14:04:44',
            ),
            40 => 
            array (
                'id' => 53,
                'title' => NULL,
                'information' => '20kL, Plate Number: CCP 6918',
                'venue' => NULL,
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => 219,
                'conforme_id' => NULL,
                'schedule_id' => 53,
                'created_at' => '2026-06-17 16:05:43',
                'updated_at' => '2026-06-17 16:05:43',
            ),
            41 => 
            array (
                'id' => 54,
                'title' => NULL,
                'information' => 'MAC',
                'venue' => NULL,
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => NULL,
                'conforme_id' => NULL,
                'schedule_id' => 54,
                'created_at' => '2026-06-18 07:36:51',
                'updated_at' => '2026-06-18 07:36:51',
            ),
            42 => 
            array (
                'id' => 55,
                'title' => 'Training of DOST 11',
                'information' => 'Training',
                'venue' => 'Davao City',
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => NULL,
                'conforme_id' => NULL,
                'schedule_id' => 55,
                'created_at' => '2026-06-18 10:41:02',
                'updated_at' => '2026-06-18 10:41:02',
            ),
            43 => 
            array (
                'id' => 56,
                'title' => 'PAB Assessment',
                'information' => 'Assessment',
                'venue' => 'RSTL',
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => NULL,
                'conforme_id' => NULL,
                'schedule_id' => 56,
                'created_at' => '2026-06-18 10:42:19',
                'updated_at' => '2026-06-18 10:42:19',
            ),
            44 => 
            array (
                'id' => 57,
                'title' => NULL,
                'information' => NULL,
                'venue' => NULL,
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => 1501,
                'conforme_id' => NULL,
                'schedule_id' => 57,
                'created_at' => '2026-06-20 22:13:40',
                'updated_at' => '2026-06-20 22:13:40',
            ),
            45 => 
            array (
                'id' => 58,
                'title' => NULL,
                'information' => 'Wellness Leave',
                'venue' => NULL,
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => NULL,
                'conforme_id' => NULL,
                'schedule_id' => 58,
                'created_at' => '2026-06-22 07:23:34',
                'updated_at' => '2026-06-22 07:23:34',
            ),
            46 => 
            array (
                'id' => 60,
                'title' => NULL,
                'information' => NULL,
                'venue' => NULL,
                'samples' => 2,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => 34,
                'conforme_id' => 844,
                'schedule_id' => 60,
                'created_at' => '2026-06-22 11:34:55',
                'updated_at' => '2026-06-22 11:34:55',
            ),
            47 => 
            array (
                'id' => 61,
                'title' => NULL,
                'information' => 'Refer to TSR # R9-072025-MET-0436',
                'venue' => NULL,
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => 821,
                'conforme_id' => 1291,
                'schedule_id' => 61,
                'created_at' => '2026-06-25 10:18:57',
                'updated_at' => '2026-06-25 10:18:57',
            ),
            48 => 
            array (
                'id' => 62,
                'title' => NULL,
                'information' => 'Refer to TSR # R9-072025-MET-0438',
                'venue' => NULL,
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => 821,
                'conforme_id' => 1291,
                'schedule_id' => 62,
                'created_at' => '2026-06-25 10:19:49',
                'updated_at' => '2026-06-25 10:19:49',
            ),
            49 => 
            array (
                'id' => 63,
                'title' => NULL,
                'information' => 'PAID, Refer to TSR # R9-062026-MET-0528',
                'venue' => NULL,
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => 1677,
                'conforme_id' => 1297,
                'schedule_id' => 63,
                'created_at' => '2026-06-29 13:54:48',
                'updated_at' => '2026-06-29 13:54:48',
            ),
            50 => 
            array (
                'id' => 64,
                'title' => NULL,
                'information' => NULL,
                'venue' => NULL,
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => NULL,
                'conforme_id' => NULL,
                'schedule_id' => 64,
                'created_at' => '2026-07-01 07:45:32',
                'updated_at' => '2026-07-01 07:45:32',
            ),
            51 => 
            array (
                'id' => 65,
                'title' => NULL,
                'information' => NULL,
                'venue' => NULL,
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => NULL,
                'conforme_id' => NULL,
                'schedule_id' => 65,
                'created_at' => '2026-07-01 07:45:46',
                'updated_at' => '2026-07-01 07:45:46',
            ),
            52 => 
            array (
                'id' => 66,
                'title' => 'Calibration of Standards',
                'information' => 'To submit standards for calibration at DOST-ITDI.',
                'venue' => 'DOST-ITDI',
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => NULL,
                'conforme_id' => NULL,
                'schedule_id' => 66,
                'created_at' => '2026-07-01 07:54:02',
                'updated_at' => '2026-07-01 07:54:02',
            ),
            53 => 
            array (
                'id' => 67,
                'title' => NULL,
                'information' => 'Plate Number: GNN403, 20kL',
                'venue' => NULL,
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => 219,
                'conforme_id' => 206,
                'schedule_id' => 67,
                'created_at' => '2026-07-02 11:56:19',
                'updated_at' => '2026-07-02 11:56:19',
            ),
            54 => 
            array (
                'id' => 68,
                'title' => 'RSTW 2026',
                'information' => NULL,
                'venue' => NULL,
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => NULL,
                'conforme_id' => NULL,
                'schedule_id' => 68,
                'created_at' => '2026-07-06 07:14:54',
                'updated_at' => '2026-07-06 07:14:54',
            ),
            55 => 
            array (
                'id' => 69,
                'title' => NULL,
                'information' => '20kL',
                'venue' => NULL,
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => 15,
                'conforme_id' => 853,
                'schedule_id' => 69,
                'created_at' => '2026-07-06 09:19:46',
                'updated_at' => '2026-07-06 09:19:46',
            ),
            56 => 
            array (
                'id' => 71,
                'title' => 'AAJ Hauling Services',
                'information' => 'Either 20 kL',
                'venue' => NULL,
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => 37,
                'conforme_id' => 871,
                'schedule_id' => 71,
                'created_at' => '2026-07-13 09:13:35',
                'updated_at' => '2026-07-28 16:22:42',
            ),
            57 => 
            array (
                'id' => 73,
                'title' => 'AAJ Hauling Services',
                'information' => '30 kL',
                'venue' => NULL,
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => 37,
                'conforme_id' => 871,
                'schedule_id' => 73,
                'created_at' => '2026-07-13 09:16:15',
                'updated_at' => '2026-08-03 13:08:49',
            ),
            58 => 
            array (
                'id' => 74,
                'title' => NULL,
                'information' => NULL,
                'venue' => NULL,
                'samples' => 2,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => 1664,
                'conforme_id' => 1266,
                'schedule_id' => 74,
                'created_at' => '2026-07-13 11:41:14',
                'updated_at' => '2026-07-13 11:41:14',
            ),
            59 => 
            array (
                'id' => 75,
                'title' => NULL,
                'information' => 'Death Anniversary of my Mother',
                'venue' => NULL,
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => NULL,
                'conforme_id' => NULL,
                'schedule_id' => 75,
                'created_at' => '2026-07-13 13:06:24',
                'updated_at' => '2026-07-13 13:06:24',
            ),
            60 => 
            array (
                'id' => 77,
                'title' => NULL,
                'information' => 'To attend my cousin\'s wedding in Cebu',
                'venue' => NULL,
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => NULL,
                'conforme_id' => NULL,
                'schedule_id' => 77,
                'created_at' => '2026-07-13 13:10:22',
                'updated_at' => '2026-07-13 13:10:22',
            ),
            61 => 
            array (
                'id' => 78,
                'title' => 'Performance Review & Document Review',
                'information' => NULL,
                'venue' => NULL,
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => NULL,
                'conforme_id' => NULL,
                'schedule_id' => 78,
                'created_at' => '2026-07-14 10:16:27',
                'updated_at' => '2026-07-14 10:16:27',
            ),
            62 => 
            array (
                'id' => 80,
                'title' => NULL,
                'information' => 'Manila',
                'venue' => NULL,
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => NULL,
                'conforme_id' => NULL,
                'schedule_id' => 80,
                'created_at' => '2026-07-20 10:48:47',
                'updated_at' => '2026-07-20 10:48:47',
            ),
            63 => 
            array (
                'id' => 81,
                'title' => NULL,
                'information' => 'On-site calibration of truck scale (30,000 kg).',
                'venue' => NULL,
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => 3873,
                'customer_id' => 20,
                'conforme_id' => NULL,
                'schedule_id' => 81,
                'created_at' => '2026-07-20 13:31:52',
                'updated_at' => '2026-07-20 13:31:52',
            ),
            64 => 
            array (
                'id' => 82,
                'title' => NULL,
                'information' => '12 kL, Contact Person: 09637754946',
                'venue' => NULL,
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => 219,
                'conforme_id' => 206,
                'schedule_id' => 82,
                'created_at' => '2026-07-20 13:47:27',
                'updated_at' => '2026-07-20 13:47:27',
            ),
            65 => 
            array (
                'id' => 83,
                'title' => NULL,
                'information' => '20kL',
                'venue' => NULL,
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => 194,
                'conforme_id' => 954,
                'schedule_id' => 83,
                'created_at' => '2026-07-21 09:14:47',
                'updated_at' => '2026-07-21 09:14:47',
            ),
            66 => 
            array (
                'id' => 84,
                'title' => NULL,
                'information' => 'Refer to QUO # 366 and 367',
                'venue' => NULL,
                'samples' => 4,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => 115,
                'conforme_id' => 510,
                'schedule_id' => 84,
                'created_at' => '2026-07-21 11:28:44',
                'updated_at' => '2026-07-21 11:28:44',
            ),
            67 => 
            array (
                'id' => 85,
                'title' => NULL,
                'information' => NULL,
                'venue' => NULL,
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => 3955,
                'customer_id' => 673,
                'conforme_id' => NULL,
                'schedule_id' => 85,
                'created_at' => '2026-07-22 08:59:12',
                'updated_at' => '2026-07-22 08:59:12',
            ),
            68 => 
            array (
                'id' => 87,
                'title' => NULL,
                'information' => '-',
                'venue' => NULL,
                'samples' => 2,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => 992,
                'conforme_id' => 854,
                'schedule_id' => 87,
                'created_at' => '2026-07-27 11:03:39',
                'updated_at' => '2026-07-27 11:03:39',
            ),
            69 => 
            array (
                'id' => 88,
                'title' => NULL,
                'information' => '20 kL',
                'venue' => NULL,
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => 787,
                'conforme_id' => 1369,
                'schedule_id' => 88,
                'created_at' => '2026-07-28 08:17:53',
                'updated_at' => '2026-07-28 08:17:53',
            ),
            70 => 
            array (
                'id' => 89,
                'title' => 'JA Group of Companies Inc.',
                'information' => '6 kL Road Tanker, Plate Number: 110100001462556, Contact Number: 09539405052,',
                'venue' => NULL,
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => 1504,
                'conforme_id' => 1083,
                'schedule_id' => 89,
                'created_at' => '2026-07-28 11:38:33',
                'updated_at' => '2026-07-28 11:39:50',
            ),
            71 => 
            array (
                'id' => 90,
                'title' => 'Mingjie Fuel Trading',
                'information' => '30 kL - 09672753257',
                'venue' => NULL,
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => 186,
                'conforme_id' => 162,
                'schedule_id' => 90,
                'created_at' => '2026-07-28 13:03:04',
                'updated_at' => '2026-09-01 14:35:09',
            ),
            72 => 
            array (
                'id' => 91,
                'title' => NULL,
                'information' => NULL,
                'venue' => NULL,
                'samples' => 2,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => 54,
                'conforme_id' => 1302,
                'schedule_id' => 91,
                'created_at' => '2026-07-29 15:10:09',
                'updated_at' => '2026-07-29 15:10:09',
            ),
            73 => 
            array (
                'id' => 92,
                'title' => NULL,
                'information' => '24kL',
                'venue' => NULL,
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => 759,
                'conforme_id' => 1381,
                'schedule_id' => 92,
                'created_at' => '2026-08-04 10:35:19',
                'updated_at' => '2026-08-04 10:35:19',
            ),
            74 => 
            array (
                'id' => 93,
                'title' => NULL,
                'information' => '6 KL Road tanker - 09539405052',
                'venue' => NULL,
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => 1504,
                'conforme_id' => 1083,
                'schedule_id' => 93,
                'created_at' => '2026-08-04 14:08:28',
                'updated_at' => '2026-08-04 14:08:28',
            ),
            75 => 
            array (
                'id' => 94,
                'title' => NULL,
                'information' => '.',
                'venue' => NULL,
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => 4461,
                'customer_id' => 1707,
                'conforme_id' => NULL,
                'schedule_id' => 94,
                'created_at' => '2026-08-04 16:12:41',
                'updated_at' => '2026-08-04 16:12:41',
            ),
            76 => 
            array (
                'id' => 95,
                'title' => 'EPR Environmental Summit & Investment Forum 2026',
                'information' => NULL,
                'venue' => 'City Gymnasium, Isabela City Basila',
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => NULL,
                'conforme_id' => NULL,
                'schedule_id' => 95,
                'created_at' => '2026-08-06 12:51:40',
                'updated_at' => '2026-08-06 12:51:40',
            ),
            77 => 
            array (
                'id' => 96,
                'title' => 'Petron Centenarian Gas Station / Suzette C. Daniel',
                'information' => 'Jobanie Jumawan - 09757627238, 20kL',
                'venue' => NULL,
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => 699,
                'conforme_id' => 354,
                'schedule_id' => 96,
                'created_at' => '2026-08-17 09:13:58',
                'updated_at' => '2026-08-20 15:06:04',
            ),
            78 => 
            array (
                'id' => 97,
                'title' => 'Wilmar Edible Oils Phils. Inc.',
                'information' => 'To render on-site calibration services to Port of Dapitan (August 24) and Wilmar Edible Oils Ph (August 25-27).',
                'venue' => NULL,
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => 4390,
                'customer_id' => 56,
                'conforme_id' => NULL,
                'schedule_id' => 97,
                'created_at' => '2026-08-17 09:38:21',
                'updated_at' => '2026-08-17 10:34:38',
            ),
            79 => 
            array (
                'id' => 98,
                'title' => 'PSCP Training',
                'information' => 'Training for PSCP',
                'venue' => 'DOST CO',
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => NULL,
                'conforme_id' => NULL,
                'schedule_id' => 98,
                'created_at' => '2026-08-17 09:47:51',
                'updated_at' => '2026-08-17 09:47:51',
            ),
            80 => 
            array (
                'id' => 99,
                'title' => 'Meeting ZCIEERD',
                'information' => 'Meeting',
                'venue' => 'Iloilo City',
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => NULL,
                'conforme_id' => NULL,
                'schedule_id' => 99,
                'created_at' => '2026-08-17 09:50:30',
                'updated_at' => '2026-08-17 09:50:30',
            ),
            81 => 
            array (
                'id' => 100,
                'title' => NULL,
                'information' => 'Personnal',
                'venue' => NULL,
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => NULL,
                'conforme_id' => NULL,
                'schedule_id' => 100,
                'created_at' => '2026-08-17 09:51:22',
                'updated_at' => '2026-08-17 09:51:22',
            ),
            82 => 
            array (
                'id' => 101,
                'title' => NULL,
                'information' => 'o render on-site calibration services to Port of Dapitan (August 24) and Wilmar Edible Oils Ph (August 25-27).',
                'venue' => NULL,
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => 4412,
                'customer_id' => 1675,
                'conforme_id' => NULL,
                'schedule_id' => 101,
                'created_at' => '2026-08-17 10:36:23',
                'updated_at' => '2026-08-17 10:36:23',
            ),
            83 => 
            array (
                'id' => 102,
                'title' => NULL,
                'information' => NULL,
                'venue' => NULL,
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => NULL,
                'conforme_id' => NULL,
                'schedule_id' => 102,
                'created_at' => '2026-08-20 08:23:21',
                'updated_at' => '2026-08-20 08:23:21',
            ),
            84 => 
            array (
                'id' => 103,
                'title' => 'Training (MAC &AAJ)',
                'information' => 'Calibration of Test Weights (MAC & AAJ)',
                'venue' => 'ITDI',
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => NULL,
                'conforme_id' => NULL,
                'schedule_id' => 103,
                'created_at' => '2026-08-20 08:26:05',
                'updated_at' => '2026-08-20 08:26:05',
            ),
            85 => 
            array (
                'id' => 104,
                'title' => NULL,
                'information' => '14 kL',
                'venue' => NULL,
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => 194,
                'conforme_id' => 954,
                'schedule_id' => 104,
                'created_at' => '2026-08-27 11:17:21',
                'updated_at' => '2026-08-27 11:17:21',
            ),
            86 => 
            array (
                'id' => 105,
                'title' => 'To attend the seminar on Disposal of Government Properties (DGP) with One-Time cleansing of PPE Account Balances',
                'information' => NULL,
                'venue' => 'Pagadian City',
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => NULL,
                'conforme_id' => NULL,
                'schedule_id' => 105,
                'created_at' => '2026-08-31 23:32:44',
                'updated_at' => '2026-08-31 23:32:44',
            ),
            87 => 
            array (
                'id' => 106,
                'title' => NULL,
                'information' => 'Tentative Schedule. assess available pick up and driver for std proving tank',
                'venue' => NULL,
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => 715,
                'conforme_id' => NULL,
                'schedule_id' => 106,
                'created_at' => '2026-09-01 10:45:33',
                'updated_at' => '2026-09-01 10:45:33',
            ),
            88 => 
            array (
                'id' => 107,
                'title' => NULL,
                'information' => 'Refer to TSR R9-102025-MET-0577, 20kL',
                'venue' => NULL,
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => 821,
                'conforme_id' => 1291,
                'schedule_id' => 107,
                'created_at' => '2026-09-08 07:58:43',
                'updated_at' => '2026-09-08 07:58:43',
            ),
            89 => 
            array (
                'id' => 108,
                'title' => NULL,
                'information' => 'R9-092025-MET-0521, 20kL',
                'venue' => NULL,
                'samples' => NULL,
                'quotation_id' => NULL,
                'tsr_id' => NULL,
                'customer_id' => 821,
                'conforme_id' => 1291,
                'schedule_id' => 108,
                'created_at' => '2026-09-08 07:59:16',
                'updated_at' => '2026-09-08 07:59:16',
            ),
        ));


    }
}
