<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class TargetBreakdownsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('target_breakdowns')->delete();
        
        \DB::table('target_breakdowns')->insert(array (
            0 => 
            array (
                'id' => 1,
                'count' => 2041,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 1,
                'laboratory_id' => 1,
                'target_id' => 1,
                'user_id' => NULL,
                'created_at' => '2025-07-02 08:43:42',
                'updated_at' => '2025-07-02 08:43:42',
            ),
            1 => 
            array (
                'id' => 2,
                'count' => 1530,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 1,
                'laboratory_id' => 2,
                'target_id' => 1,
                'user_id' => NULL,
                'created_at' => '2025-07-02 08:43:42',
                'updated_at' => '2025-07-02 08:43:42',
            ),
            2 => 
            array (
                'id' => 3,
                'count' => 1530,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 1,
                'laboratory_id' => 3,
                'target_id' => 1,
                'user_id' => NULL,
                'created_at' => '2025-07-02 08:43:42',
                'updated_at' => '2025-07-02 08:43:42',
            ),
            3 => 
            array (
                'id' => 4,
                'count' => 4591,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 2,
                'laboratory_id' => 1,
                'target_id' => 1,
                'user_id' => NULL,
                'created_at' => '2025-07-02 08:43:42',
                'updated_at' => '2025-07-02 08:43:42',
            ),
            4 => 
            array (
                'id' => 5,
                'count' => 4590,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 2,
                'laboratory_id' => 2,
                'target_id' => 1,
                'user_id' => NULL,
                'created_at' => '2025-07-02 08:43:42',
                'updated_at' => '2025-07-02 08:43:42',
            ),
            5 => 
            array (
                'id' => 6,
                'count' => 1530,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 2,
                'laboratory_id' => 3,
                'target_id' => 1,
                'user_id' => NULL,
                'created_at' => '2025-07-02 08:43:42',
                'updated_at' => '2025-07-02 08:43:42',
            ),
            6 => 
            array (
                'id' => 7,
                'count' => 680,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 3,
                'laboratory_id' => 1,
                'target_id' => 1,
                'user_id' => NULL,
                'created_at' => '2025-07-02 08:43:42',
                'updated_at' => '2025-07-02 08:43:42',
            ),
            7 => 
            array (
                'id' => 8,
                'count' => 680,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 3,
                'laboratory_id' => 2,
                'target_id' => 1,
                'user_id' => NULL,
                'created_at' => '2025-07-02 08:43:42',
                'updated_at' => '2025-07-02 08:43:42',
            ),
            8 => 
            array (
                'id' => 9,
                'count' => 680,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 3,
                'laboratory_id' => 3,
                'target_id' => 1,
                'user_id' => NULL,
                'created_at' => '2025-07-02 08:43:42',
                'updated_at' => '2025-07-02 08:43:42',
            ),
            9 => 
            array (
                'id' => 10,
                'count' => 223,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 1,
                'objective_id' => 4,
                'laboratory_id' => NULL,
                'target_id' => 1,
                'user_id' => NULL,
                'created_at' => '2025-07-02 08:43:42',
                'updated_at' => '2025-07-02 08:43:42',
            ),
            10 => 
            array (
                'id' => 11,
                'count' => 360,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 1,
                'objective_id' => 5,
                'laboratory_id' => NULL,
                'target_id' => 1,
                'user_id' => NULL,
                'created_at' => '2025-07-02 08:43:42',
                'updated_at' => '2025-07-02 08:43:42',
            ),
            11 => 
            array (
                'id' => 14,
                'count' => 2856280,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 1,
                'is_consolidated' => 0,
                'objective_id' => 6,
                'laboratory_id' => 1,
                'target_id' => 1,
                'user_id' => NULL,
                'created_at' => '2025-07-02 08:43:42',
                'updated_at' => '2025-07-02 08:43:42',
            ),
            12 => 
            array (
                'id' => 15,
                'count' => 2142210,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 1,
                'is_consolidated' => 0,
                'objective_id' => 6,
                'laboratory_id' => 2,
                'target_id' => 1,
                'user_id' => NULL,
                'created_at' => '2025-07-02 08:43:42',
                'updated_at' => '2025-07-02 08:43:42',
            ),
            13 => 
            array (
                'id' => 16,
                'count' => 2142210,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 1,
                'is_consolidated' => 0,
                'objective_id' => 6,
                'laboratory_id' => 3,
                'target_id' => 1,
                'user_id' => NULL,
                'created_at' => '2025-07-02 08:43:42',
                'updated_at' => '2025-07-02 08:43:42',
            ),
            14 => 
            array (
                'id' => 17,
                'count' => 202005,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 1,
                'is_consolidated' => 0,
                'objective_id' => 7,
                'laboratory_id' => 1,
                'target_id' => 1,
                'user_id' => NULL,
                'created_at' => '2025-07-02 08:43:42',
                'updated_at' => '2025-07-02 08:43:42',
            ),
            15 => 
            array (
                'id' => 18,
                'count' => 202005,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 1,
                'is_consolidated' => 0,
                'objective_id' => 7,
                'laboratory_id' => 2,
                'target_id' => 1,
                'user_id' => NULL,
                'created_at' => '2025-07-02 08:43:42',
                'updated_at' => '2025-07-02 08:43:42',
            ),
            16 => 
            array (
                'id' => 19,
                'count' => 404010,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 1,
                'is_consolidated' => 0,
                'objective_id' => 7,
                'laboratory_id' => 3,
                'target_id' => 1,
                'user_id' => NULL,
                'created_at' => '2025-07-02 08:43:42',
                'updated_at' => '2025-07-02 08:43:42',
            ),
            17 => 
            array (
                'id' => 20,
                'count' => 3668,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 8,
                'laboratory_id' => 1,
                'target_id' => 1,
                'user_id' => NULL,
                'created_at' => '2025-07-02 08:43:42',
                'updated_at' => '2025-07-02 08:43:42',
            ),
            18 => 
            array (
                'id' => 21,
                'count' => 2548,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 8,
                'laboratory_id' => 2,
                'target_id' => 1,
                'user_id' => NULL,
                'created_at' => '2025-07-02 08:43:42',
                'updated_at' => '2025-07-02 08:43:42',
            ),
            19 => 
            array (
                'id' => 22,
                'count' => 1296,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 8,
                'laboratory_id' => 3,
                'target_id' => 1,
                'user_id' => NULL,
                'created_at' => '2025-07-02 08:43:42',
                'updated_at' => '2025-07-02 08:43:42',
            ),
            20 => 
            array (
                'id' => 23,
                'count' => 544,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 9,
                'laboratory_id' => 1,
                'target_id' => 1,
                'user_id' => NULL,
                'created_at' => '2025-07-02 08:43:42',
                'updated_at' => '2025-07-02 08:43:42',
            ),
            21 => 
            array (
                'id' => 24,
                'count' => 524,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 9,
                'laboratory_id' => 2,
                'target_id' => 1,
                'user_id' => NULL,
                'created_at' => '2025-07-02 08:43:42',
                'updated_at' => '2025-07-02 08:43:42',
            ),
            22 => 
            array (
                'id' => 25,
                'count' => 1500,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 9,
                'laboratory_id' => 3,
                'target_id' => 1,
                'user_id' => NULL,
                'created_at' => '2025-07-02 08:43:42',
                'updated_at' => '2025-07-02 08:43:42',
            ),
            23 => 
            array (
                'id' => 26,
                'count' => 0,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 1,
                'laboratory_id' => 4,
                'target_id' => 1,
                'user_id' => NULL,
                'created_at' => '2025-07-02 08:43:42',
                'updated_at' => '2025-07-02 08:43:42',
            ),
            24 => 
            array (
                'id' => 27,
                'count' => 0,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 2,
                'laboratory_id' => 4,
                'target_id' => 1,
                'user_id' => NULL,
                'created_at' => '2025-07-02 08:43:42',
                'updated_at' => '2025-07-02 08:43:42',
            ),
            25 => 
            array (
                'id' => 28,
                'count' => 0,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 3,
                'laboratory_id' => 4,
                'target_id' => 1,
                'user_id' => NULL,
                'created_at' => '2025-07-02 08:43:42',
                'updated_at' => '2025-07-02 08:43:42',
            ),
            26 => 
            array (
                'id' => 31,
                'count' => 0,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 1,
                'is_consolidated' => 0,
                'objective_id' => 6,
                'laboratory_id' => 4,
                'target_id' => 1,
                'user_id' => NULL,
                'created_at' => '2025-07-02 08:43:42',
                'updated_at' => '2025-07-02 08:43:42',
            ),
            27 => 
            array (
                'id' => 32,
                'count' => 0,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 1,
                'is_consolidated' => 0,
                'objective_id' => 7,
                'laboratory_id' => 4,
                'target_id' => 1,
                'user_id' => NULL,
                'created_at' => '2025-07-02 08:43:42',
                'updated_at' => '2025-07-02 08:43:42',
            ),
            28 => 
            array (
                'id' => 33,
                'count' => 0,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 8,
                'laboratory_id' => 4,
                'target_id' => 1,
                'user_id' => NULL,
                'created_at' => '2025-07-02 08:43:42',
                'updated_at' => '2025-07-02 08:43:42',
            ),
            29 => 
            array (
                'id' => 34,
                'count' => 0,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 9,
                'laboratory_id' => 4,
                'target_id' => 1,
                'user_id' => NULL,
                'created_at' => '2025-07-02 08:43:42',
                'updated_at' => '2025-07-02 08:43:42',
            ),
            30 => 
            array (
                'id' => 35,
                'count' => 1600,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 1,
                'laboratory_id' => 1,
                'target_id' => 2,
                'user_id' => NULL,
                'created_at' => '2026-01-05 14:55:16',
                'updated_at' => '2026-04-13 10:32:28',
            ),
            31 => 
            array (
                'id' => 36,
                'count' => 1600,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 1,
                'laboratory_id' => 2,
                'target_id' => 2,
                'user_id' => NULL,
                'created_at' => '2026-01-05 14:55:16',
                'updated_at' => '2026-04-13 10:32:28',
            ),
            32 => 
            array (
                'id' => 37,
                'count' => 1900,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 1,
                'laboratory_id' => 3,
                'target_id' => 2,
                'user_id' => NULL,
                'created_at' => '2026-01-05 14:55:17',
                'updated_at' => '2026-04-13 10:32:28',
            ),
            33 => 
            array (
                'id' => 38,
                'count' => 100,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 1,
                'laboratory_id' => 4,
                'target_id' => 2,
                'user_id' => NULL,
                'created_at' => '2026-01-05 14:55:17',
                'updated_at' => '2026-04-13 10:32:28',
            ),
            34 => 
            array (
                'id' => 39,
                'count' => 4500,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 2,
                'laboratory_id' => 1,
                'target_id' => 2,
                'user_id' => NULL,
                'created_at' => '2026-01-05 14:55:17',
                'updated_at' => '2026-04-13 10:33:22',
            ),
            35 => 
            array (
                'id' => 40,
                'count' => 3200,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 2,
                'laboratory_id' => 2,
                'target_id' => 2,
                'user_id' => NULL,
                'created_at' => '2026-01-05 14:55:17',
                'updated_at' => '2026-04-13 10:33:22',
            ),
            36 => 
            array (
                'id' => 41,
                'count' => 1900,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 2,
                'laboratory_id' => 3,
                'target_id' => 2,
                'user_id' => NULL,
                'created_at' => '2026-01-05 14:55:17',
                'updated_at' => '2026-04-13 10:33:22',
            ),
            37 => 
            array (
                'id' => 42,
                'count' => 600,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 2,
                'laboratory_id' => 4,
                'target_id' => 2,
                'user_id' => NULL,
                'created_at' => '2026-01-05 14:55:17',
                'updated_at' => '2026-04-13 10:33:22',
            ),
            38 => 
            array (
                'id' => 43,
                'count' => 650,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 3,
                'laboratory_id' => 1,
                'target_id' => 2,
                'user_id' => NULL,
                'created_at' => '2026-01-05 14:55:17',
                'updated_at' => '2026-04-13 10:34:51',
            ),
            39 => 
            array (
                'id' => 44,
                'count' => 530,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 3,
                'laboratory_id' => 2,
                'target_id' => 2,
                'user_id' => NULL,
                'created_at' => '2026-01-05 14:55:17',
                'updated_at' => '2026-04-13 10:34:51',
            ),
            40 => 
            array (
                'id' => 45,
                'count' => 900,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 3,
                'laboratory_id' => 3,
                'target_id' => 2,
                'user_id' => NULL,
                'created_at' => '2026-01-05 14:55:17',
                'updated_at' => '2026-04-13 10:34:51',
            ),
            41 => 
            array (
                'id' => 46,
                'count' => 20,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 3,
                'laboratory_id' => 4,
                'target_id' => 2,
                'user_id' => NULL,
                'created_at' => '2026-01-05 14:55:17',
                'updated_at' => '2026-04-13 10:34:51',
            ),
            42 => 
            array (
                'id' => 47,
                'count' => 200,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 1,
                'objective_id' => 4,
                'laboratory_id' => NULL,
                'target_id' => 2,
                'user_id' => NULL,
                'created_at' => '2026-01-05 14:55:17',
                'updated_at' => '2026-04-13 10:36:04',
            ),
            43 => 
            array (
                'id' => 48,
                'count' => 189,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 5,
                'laboratory_id' => 1,
                'target_id' => 2,
                'user_id' => NULL,
                'created_at' => '2026-01-05 14:55:17',
                'updated_at' => '2026-04-13 10:36:16',
            ),
            44 => 
            array (
                'id' => 49,
                'count' => 189,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 5,
                'laboratory_id' => 2,
                'target_id' => 2,
                'user_id' => NULL,
                'created_at' => '2026-01-05 14:55:17',
                'updated_at' => '2026-04-13 10:36:16',
            ),
            45 => 
            array (
                'id' => 50,
                'count' => 189,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 5,
                'laboratory_id' => 3,
                'target_id' => 2,
                'user_id' => NULL,
                'created_at' => '2026-01-05 14:55:17',
                'updated_at' => '2026-04-13 10:36:16',
            ),
            46 => 
            array (
                'id' => 51,
                'count' => 188,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 5,
                'laboratory_id' => 4,
                'target_id' => 2,
                'user_id' => NULL,
                'created_at' => '2026-01-05 14:55:17',
                'updated_at' => '2026-04-13 10:36:16',
            ),
            47 => 
            array (
                'id' => 52,
                'count' => 3000000,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 1,
                'is_consolidated' => 0,
                'objective_id' => 6,
                'laboratory_id' => 1,
                'target_id' => 2,
                'user_id' => NULL,
                'created_at' => '2026-01-05 14:55:17',
                'updated_at' => '2026-04-13 10:36:55',
            ),
            48 => 
            array (
                'id' => 53,
                'count' => 1500000,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 1,
                'is_consolidated' => 0,
                'objective_id' => 6,
                'laboratory_id' => 2,
                'target_id' => 2,
                'user_id' => NULL,
                'created_at' => '2026-01-05 14:55:17',
                'updated_at' => '2026-04-13 10:36:55',
            ),
            49 => 
            array (
                'id' => 54,
                'count' => 1600000,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 1,
                'is_consolidated' => 0,
                'objective_id' => 6,
                'laboratory_id' => 3,
                'target_id' => 2,
                'user_id' => NULL,
                'created_at' => '2026-01-05 14:55:17',
                'updated_at' => '2026-04-13 10:36:55',
            ),
            50 => 
            array (
                'id' => 55,
                'count' => 100000,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 1,
                'is_consolidated' => 0,
                'objective_id' => 6,
                'laboratory_id' => 4,
                'target_id' => 2,
                'user_id' => NULL,
                'created_at' => '2026-01-05 14:55:17',
                'updated_at' => '2026-04-13 10:36:55',
            ),
            51 => 
            array (
                'id' => 56,
                'count' => 250000,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 1,
                'is_consolidated' => 0,
                'objective_id' => 7,
                'laboratory_id' => 1,
                'target_id' => 2,
                'user_id' => NULL,
                'created_at' => '2026-01-05 14:55:17',
                'updated_at' => '2026-04-13 11:01:42',
            ),
            52 => 
            array (
                'id' => 57,
                'count' => 200000,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 1,
                'is_consolidated' => 0,
                'objective_id' => 7,
                'laboratory_id' => 2,
                'target_id' => 2,
                'user_id' => NULL,
                'created_at' => '2026-01-05 14:55:17',
                'updated_at' => '2026-04-13 11:01:42',
            ),
            53 => 
            array (
                'id' => 58,
                'count' => 1500000,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 1,
                'is_consolidated' => 0,
                'objective_id' => 7,
                'laboratory_id' => 3,
                'target_id' => 2,
                'user_id' => NULL,
                'created_at' => '2026-01-05 14:55:17',
                'updated_at' => '2026-04-13 11:01:42',
            ),
            54 => 
            array (
                'id' => 59,
                'count' => 50000,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 1,
                'is_consolidated' => 0,
                'objective_id' => 7,
                'laboratory_id' => 4,
                'target_id' => 2,
                'user_id' => NULL,
                'created_at' => '2026-01-05 14:55:17',
                'updated_at' => '2026-04-13 11:01:42',
            ),
            55 => 
            array (
                'id' => 60,
                'count' => 4200,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 8,
                'laboratory_id' => 1,
                'target_id' => 2,
                'user_id' => NULL,
                'created_at' => '2026-01-05 14:55:17',
                'updated_at' => '2026-04-13 11:05:31',
            ),
            56 => 
            array (
                'id' => 61,
                'count' => 2500,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 8,
                'laboratory_id' => 2,
                'target_id' => 2,
                'user_id' => NULL,
                'created_at' => '2026-01-05 14:55:17',
                'updated_at' => '2026-04-13 11:05:31',
            ),
            57 => 
            array (
                'id' => 62,
                'count' => 1300,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 8,
                'laboratory_id' => 3,
                'target_id' => 2,
                'user_id' => NULL,
                'created_at' => '2026-01-05 14:55:17',
                'updated_at' => '2026-04-13 11:05:31',
            ),
            58 => 
            array (
                'id' => 63,
                'count' => 500,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 8,
                'laboratory_id' => 4,
                'target_id' => 2,
                'user_id' => NULL,
                'created_at' => '2026-01-05 14:55:17',
                'updated_at' => '2026-04-13 11:05:31',
            ),
            59 => 
            array (
                'id' => 64,
                'count' => 450,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 9,
                'laboratory_id' => 1,
                'target_id' => 2,
                'user_id' => NULL,
                'created_at' => '2026-01-05 14:55:17',
                'updated_at' => '2026-04-13 11:05:39',
            ),
            60 => 
            array (
                'id' => 65,
                'count' => 200,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 9,
                'laboratory_id' => 2,
                'target_id' => 2,
                'user_id' => NULL,
                'created_at' => '2026-01-05 14:55:17',
                'updated_at' => '2026-04-13 11:05:39',
            ),
            61 => 
            array (
                'id' => 66,
                'count' => 700,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 9,
                'laboratory_id' => 3,
                'target_id' => 2,
                'user_id' => NULL,
                'created_at' => '2026-01-05 14:55:17',
                'updated_at' => '2026-04-13 11:05:39',
            ),
            62 => 
            array (
                'id' => 67,
                'count' => 0,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 9,
                'laboratory_id' => 4,
                'target_id' => 2,
                'user_id' => NULL,
                'created_at' => '2026-01-05 14:55:17',
                'updated_at' => '2026-04-13 11:05:39',
            ),
            63 => 
            array (
                'id' => 68,
                'count' => 0,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 10,
                'laboratory_id' => 1,
                'target_id' => 2,
                'user_id' => NULL,
                'created_at' => '2026-01-05 14:55:17',
                'updated_at' => '2026-01-05 14:55:17',
            ),
            64 => 
            array (
                'id' => 69,
                'count' => 0,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 10,
                'laboratory_id' => 2,
                'target_id' => 2,
                'user_id' => NULL,
                'created_at' => '2026-01-05 14:55:17',
                'updated_at' => '2026-01-05 14:55:17',
            ),
            65 => 
            array (
                'id' => 70,
                'count' => 0,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 10,
                'laboratory_id' => 3,
                'target_id' => 2,
                'user_id' => NULL,
                'created_at' => '2026-01-05 14:55:17',
                'updated_at' => '2026-01-05 14:55:17',
            ),
            66 => 
            array (
                'id' => 71,
                'count' => 0,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 10,
                'laboratory_id' => 4,
                'target_id' => 2,
                'user_id' => NULL,
                'created_at' => '2026-01-05 14:55:17',
                'updated_at' => '2026-01-05 14:55:17',
            ),
            67 => 
            array (
                'id' => 72,
                'count' => 0,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 11,
                'laboratory_id' => 1,
                'target_id' => 2,
                'user_id' => NULL,
                'created_at' => '2026-01-05 14:55:17',
                'updated_at' => '2026-01-05 14:55:17',
            ),
            68 => 
            array (
                'id' => 73,
                'count' => 0,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 11,
                'laboratory_id' => 2,
                'target_id' => 2,
                'user_id' => NULL,
                'created_at' => '2026-01-05 14:55:17',
                'updated_at' => '2026-01-05 14:55:17',
            ),
            69 => 
            array (
                'id' => 74,
                'count' => 0,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 11,
                'laboratory_id' => 3,
                'target_id' => 2,
                'user_id' => NULL,
                'created_at' => '2026-01-05 14:55:17',
                'updated_at' => '2026-01-05 14:55:17',
            ),
            70 => 
            array (
                'id' => 75,
                'count' => 0,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 11,
                'laboratory_id' => 4,
                'target_id' => 2,
                'user_id' => NULL,
                'created_at' => '2026-01-05 14:55:17',
                'updated_at' => '2026-01-05 14:55:17',
            ),
            71 => 
            array (
                'id' => 76,
                'count' => 0,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 12,
                'laboratory_id' => 1,
                'target_id' => 2,
                'user_id' => NULL,
                'created_at' => '2026-01-05 14:55:17',
                'updated_at' => '2026-01-05 14:55:17',
            ),
            72 => 
            array (
                'id' => 77,
                'count' => 0,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 12,
                'laboratory_id' => 2,
                'target_id' => 2,
                'user_id' => NULL,
                'created_at' => '2026-01-05 14:55:17',
                'updated_at' => '2026-01-05 14:55:17',
            ),
            73 => 
            array (
                'id' => 78,
                'count' => 0,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 12,
                'laboratory_id' => 3,
                'target_id' => 2,
                'user_id' => NULL,
                'created_at' => '2026-01-05 14:55:17',
                'updated_at' => '2026-01-05 14:55:17',
            ),
            74 => 
            array (
                'id' => 79,
                'count' => 0,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 12,
                'laboratory_id' => 4,
                'target_id' => 2,
                'user_id' => NULL,
                'created_at' => '2026-01-05 14:55:17',
                'updated_at' => '2026-01-05 14:55:17',
            ),
            75 => 
            array (
                'id' => 80,
                'count' => 0,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 13,
                'laboratory_id' => 1,
                'target_id' => 2,
                'user_id' => NULL,
                'created_at' => '2026-01-05 14:55:17',
                'updated_at' => '2026-01-05 14:55:17',
            ),
            76 => 
            array (
                'id' => 81,
                'count' => 0,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 13,
                'laboratory_id' => 2,
                'target_id' => 2,
                'user_id' => NULL,
                'created_at' => '2026-01-05 14:55:17',
                'updated_at' => '2026-01-05 14:55:17',
            ),
            77 => 
            array (
                'id' => 82,
                'count' => 0,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 13,
                'laboratory_id' => 3,
                'target_id' => 2,
                'user_id' => NULL,
                'created_at' => '2026-01-05 14:55:17',
                'updated_at' => '2026-01-05 14:55:17',
            ),
            78 => 
            array (
                'id' => 83,
                'count' => 0,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 13,
                'laboratory_id' => 4,
                'target_id' => 2,
                'user_id' => NULL,
                'created_at' => '2026-01-05 14:55:17',
                'updated_at' => '2026-01-05 14:55:17',
            ),
        ));
        
        
    }
}