<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class TargetBreakdownsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('target_breakdowns')->delete();
        
        \DB::table('target_breakdowns')->insert(array (
            0 => 
            array (
                'id' => 1,
                'count' => 2041,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 1,
                'laboratory_id' => 1,
                'target_id' => 1,
                'user_id' => NULL,
                'created_at' => '2025-07-02 08:43:42',
                'updated_at' => '2025-07-02 08:43:42',
            ),
            1 => 
            array (
                'id' => 2,
                'count' => 1530,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 1,
                'laboratory_id' => 2,
                'target_id' => 1,
                'user_id' => NULL,
                'created_at' => '2025-07-02 08:43:42',
                'updated_at' => '2025-07-02 08:43:42',
            ),
            2 => 
            array (
                'id' => 3,
                'count' => 1530,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 1,
                'laboratory_id' => 3,
                'target_id' => 1,
                'user_id' => NULL,
                'created_at' => '2025-07-02 08:43:42',
                'updated_at' => '2025-07-02 08:43:42',
            ),
            3 => 
            array (
                'id' => 4,
                'count' => 4591,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 2,
                'laboratory_id' => 1,
                'target_id' => 1,
                'user_id' => NULL,
                'created_at' => '2025-07-02 08:43:42',
                'updated_at' => '2025-07-02 08:43:42',
            ),
            4 => 
            array (
                'id' => 5,
                'count' => 4590,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 2,
                'laboratory_id' => 2,
                'target_id' => 1,
                'user_id' => NULL,
                'created_at' => '2025-07-02 08:43:42',
                'updated_at' => '2025-07-02 08:43:42',
            ),
            5 => 
            array (
                'id' => 6,
                'count' => 1530,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 2,
                'laboratory_id' => 3,
                'target_id' => 1,
                'user_id' => NULL,
                'created_at' => '2025-07-02 08:43:42',
                'updated_at' => '2025-07-02 08:43:42',
            ),
            6 => 
            array (
                'id' => 7,
                'count' => 680,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 3,
                'laboratory_id' => 1,
                'target_id' => 1,
                'user_id' => NULL,
                'created_at' => '2025-07-02 08:43:42',
                'updated_at' => '2025-07-02 08:43:42',
            ),
            7 => 
            array (
                'id' => 8,
                'count' => 680,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 3,
                'laboratory_id' => 2,
                'target_id' => 1,
                'user_id' => NULL,
                'created_at' => '2025-07-02 08:43:42',
                'updated_at' => '2025-07-02 08:43:42',
            ),
            8 => 
            array (
                'id' => 9,
                'count' => 680,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 3,
                'laboratory_id' => 3,
                'target_id' => 1,
                'user_id' => NULL,
                'created_at' => '2025-07-02 08:43:42',
                'updated_at' => '2025-07-02 08:43:42',
            ),
            9 => 
            array (
                'id' => 10,
                'count' => 223,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 1,
                'objective_id' => 4,
                'laboratory_id' => NULL,
                'target_id' => 1,
                'user_id' => NULL,
                'created_at' => '2025-07-02 08:43:42',
                'updated_at' => '2025-07-02 08:43:42',
            ),
            10 => 
            array (
                'id' => 11,
                'count' => 360,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 1,
                'objective_id' => 5,
                'laboratory_id' => NULL,
                'target_id' => 1,
                'user_id' => NULL,
                'created_at' => '2025-07-02 08:43:42',
                'updated_at' => '2025-07-02 08:43:42',
            ),
            11 => 
            array (
                'id' => 14,
                'count' => 2856280,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 1,
                'is_consolidated' => 0,
                'objective_id' => 6,
                'laboratory_id' => 1,
                'target_id' => 1,
                'user_id' => NULL,
                'created_at' => '2025-07-02 08:43:42',
                'updated_at' => '2025-07-02 08:43:42',
            ),
            12 => 
            array (
                'id' => 15,
                'count' => 2142210,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 1,
                'is_consolidated' => 0,
                'objective_id' => 6,
                'laboratory_id' => 2,
                'target_id' => 1,
                'user_id' => NULL,
                'created_at' => '2025-07-02 08:43:42',
                'updated_at' => '2025-07-02 08:43:42',
            ),
            13 => 
            array (
                'id' => 16,
                'count' => 2142210,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 1,
                'is_consolidated' => 0,
                'objective_id' => 6,
                'laboratory_id' => 3,
                'target_id' => 1,
                'user_id' => NULL,
                'created_at' => '2025-07-02 08:43:42',
                'updated_at' => '2025-07-02 08:43:42',
            ),
            14 => 
            array (
                'id' => 17,
                'count' => 202005,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 1,
                'is_consolidated' => 0,
                'objective_id' => 7,
                'laboratory_id' => 1,
                'target_id' => 1,
                'user_id' => NULL,
                'created_at' => '2025-07-02 08:43:42',
                'updated_at' => '2025-07-02 08:43:42',
            ),
            15 => 
            array (
                'id' => 18,
                'count' => 202005,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 1,
                'is_consolidated' => 0,
                'objective_id' => 7,
                'laboratory_id' => 2,
                'target_id' => 1,
                'user_id' => NULL,
                'created_at' => '2025-07-02 08:43:42',
                'updated_at' => '2025-07-02 08:43:42',
            ),
            16 => 
            array (
                'id' => 19,
                'count' => 404010,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 1,
                'is_consolidated' => 0,
                'objective_id' => 7,
                'laboratory_id' => 3,
                'target_id' => 1,
                'user_id' => NULL,
                'created_at' => '2025-07-02 08:43:42',
                'updated_at' => '2025-07-02 08:43:42',
            ),
            17 => 
            array (
                'id' => 20,
                'count' => 3668,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 8,
                'laboratory_id' => 1,
                'target_id' => 1,
                'user_id' => NULL,
                'created_at' => '2025-07-02 08:43:42',
                'updated_at' => '2025-07-02 08:43:42',
            ),
            18 => 
            array (
                'id' => 21,
                'count' => 2548,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 8,
                'laboratory_id' => 2,
                'target_id' => 1,
                'user_id' => NULL,
                'created_at' => '2025-07-02 08:43:42',
                'updated_at' => '2025-07-02 08:43:42',
            ),
            19 => 
            array (
                'id' => 22,
                'count' => 1296,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 8,
                'laboratory_id' => 3,
                'target_id' => 1,
                'user_id' => NULL,
                'created_at' => '2025-07-02 08:43:42',
                'updated_at' => '2025-07-02 08:43:42',
            ),
            20 => 
            array (
                'id' => 23,
                'count' => 544,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 9,
                'laboratory_id' => 1,
                'target_id' => 1,
                'user_id' => NULL,
                'created_at' => '2025-07-02 08:43:42',
                'updated_at' => '2025-07-02 08:43:42',
            ),
            21 => 
            array (
                'id' => 24,
                'count' => 524,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 9,
                'laboratory_id' => 2,
                'target_id' => 1,
                'user_id' => NULL,
                'created_at' => '2025-07-02 08:43:42',
                'updated_at' => '2025-07-02 08:43:42',
            ),
            22 => 
            array (
                'id' => 25,
                'count' => 1500,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 9,
                'laboratory_id' => 3,
                'target_id' => 1,
                'user_id' => NULL,
                'created_at' => '2025-07-02 08:43:42',
                'updated_at' => '2025-07-02 08:43:42',
            ),
            23 => 
            array (
                'id' => 26,
                'count' => 0,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 1,
                'laboratory_id' => 4,
                'target_id' => 1,
                'user_id' => NULL,
                'created_at' => '2025-07-02 08:43:42',
                'updated_at' => '2025-07-02 08:43:42',
            ),
            24 => 
            array (
                'id' => 27,
                'count' => 0,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 2,
                'laboratory_id' => 4,
                'target_id' => 1,
                'user_id' => NULL,
                'created_at' => '2025-07-02 08:43:42',
                'updated_at' => '2025-07-02 08:43:42',
            ),
            25 => 
            array (
                'id' => 28,
                'count' => 0,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 3,
                'laboratory_id' => 4,
                'target_id' => 1,
                'user_id' => NULL,
                'created_at' => '2025-07-02 08:43:42',
                'updated_at' => '2025-07-02 08:43:42',
            ),
            26 => 
            array (
                'id' => 31,
                'count' => 0,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 1,
                'is_consolidated' => 0,
                'objective_id' => 6,
                'laboratory_id' => 4,
                'target_id' => 1,
                'user_id' => NULL,
                'created_at' => '2025-07-02 08:43:42',
                'updated_at' => '2025-07-02 08:43:42',
            ),
            27 => 
            array (
                'id' => 32,
                'count' => 0,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 1,
                'is_consolidated' => 0,
                'objective_id' => 7,
                'laboratory_id' => 4,
                'target_id' => 1,
                'user_id' => NULL,
                'created_at' => '2025-07-02 08:43:42',
                'updated_at' => '2025-07-02 08:43:42',
            ),
            28 => 
            array (
                'id' => 33,
                'count' => 0,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 8,
                'laboratory_id' => 4,
                'target_id' => 1,
                'user_id' => NULL,
                'created_at' => '2025-07-02 08:43:42',
                'updated_at' => '2025-07-02 08:43:42',
            ),
            29 => 
            array (
                'id' => 34,
                'count' => 0,
                'accom' => 0,
                'is_set' => 0,
                'is_amount' => 0,
                'is_consolidated' => 0,
                'objective_id' => 9,
                'laboratory_id' => 4,
                'target_id' => 1,
                'user_id' => NULL,
                'created_at' => '2025-07-02 08:43:42',
                'updated_at' => '2025-07-02 08:43:42',
            ),
        ));
        
        
    }
}