<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UserRolesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('user_roles')->delete();

        \DB::table('user_roles')->insert(array (
            0 => 
            array (
                'id' => 1,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => NULL,
                'role_id' => 1,
                'user_id' => 1,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-02-11 22:59:44',
                'updated_at' => '2026-02-11 22:59:44',
            ),
            1 => 
            array (
                'id' => 2,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => NULL,
                'role_id' => 4,
                'user_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-02-11 23:26:59',
                'updated_at' => '2026-02-11 23:26:59',
            ),
            2 => 
            array (
                'id' => 3,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => NULL,
                'role_id' => 2,
                'user_id' => 3,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-02-11 23:33:36',
                'updated_at' => '2026-02-11 23:33:36',
            ),
            3 => 
            array (
                'id' => 4,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 1,
                'role_id' => 3,
                'user_id' => 4,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-02-11 23:36:00',
                'updated_at' => '2026-02-11 23:36:00',
            ),
            4 => 
            array (
                'id' => 5,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 4,
                'role_id' => 3,
                'user_id' => 5,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-02-11 23:37:54',
                'updated_at' => '2026-02-11 23:37:54',
            ),
            5 => 
            array (
                'id' => 6,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 1,
                'role_id' => 5,
                'user_id' => 6,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-02-11 23:41:38',
                'updated_at' => '2026-02-11 23:41:38',
            ),
            6 => 
            array (
                'id' => 7,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 1,
                'role_id' => 5,
                'user_id' => 7,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-02-11 23:44:47',
                'updated_at' => '2026-02-11 23:44:47',
            ),
            7 => 
            array (
                'id' => 8,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 1,
                'role_id' => 5,
                'user_id' => 8,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-02-11 23:46:39',
                'updated_at' => '2026-02-11 23:46:39',
            ),
            8 => 
            array (
                'id' => 9,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 2,
                'role_id' => 5,
                'user_id' => 9,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-02-11 23:48:09',
                'updated_at' => '2026-02-11 23:48:09',
            ),
            9 => 
            array (
                'id' => 10,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 2,
                'role_id' => 5,
                'user_id' => 10,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-02-11 23:49:01',
                'updated_at' => '2026-02-11 23:49:01',
            ),
            10 => 
            array (
                'id' => 11,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 2,
                'role_id' => 5,
                'user_id' => 11,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-02-11 23:49:53',
                'updated_at' => '2026-02-11 23:49:53',
            ),
            11 => 
            array (
                'id' => 12,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 3,
                'role_id' => 10,
                'user_id' => 12,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-02-12 00:23:47',
                'updated_at' => '2026-02-12 00:23:47',
            ),
            12 => 
            array (
                'id' => 13,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 3,
                'role_id' => 10,
                'user_id' => 13,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-02-12 00:25:20',
                'updated_at' => '2026-02-12 00:25:20',
            ),
            13 => 
            array (
                'id' => 14,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 3,
                'role_id' => 10,
                'user_id' => 14,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-02-12 00:26:19',
                'updated_at' => '2026-02-12 00:26:19',
            ),
            14 => 
            array (
                'id' => 15,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 2,
                'role_id' => 9,
                'user_id' => 15,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-02-12 00:29:09',
                'updated_at' => '2026-02-12 00:29:09',
            ),
            15 => 
            array (
                'id' => 16,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 1,
                'role_id' => 9,
                'user_id' => 16,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-02-12 00:30:34',
                'updated_at' => '2026-02-12 00:30:34',
            ),
            16 => 
            array (
                'id' => 17,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => NULL,
                'role_id' => 8,
                'user_id' => 17,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-02-12 00:31:39',
                'updated_at' => '2026-02-12 00:31:39',
            ),
            17 => 
            array (
                'id' => 18,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 3,
                'role_id' => 9,
                'user_id' => 18,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-02-12 00:33:43',
                'updated_at' => '2026-02-12 00:33:43',
            ),
            18 => 
            array (
                'id' => 19,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => NULL,
                'role_id' => 7,
                'user_id' => 19,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-02-12 00:54:07',
                'updated_at' => '2026-02-12 00:54:07',
            ),
            19 => 
            array (
                'id' => 20,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => NULL,
                'role_id' => 6,
                'user_id' => 20,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-02-12 00:54:53',
                'updated_at' => '2026-02-12 00:54:53',
            ),
            20 => 
            array (
                'id' => 21,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => NULL,
                'role_id' => 7,
                'user_id' => 21,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-02-12 00:59:22',
                'updated_at' => '2026-02-12 00:59:22',
            ),
            21 => 
            array (
                'id' => 22,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => NULL,
                'role_id' => 6,
                'user_id' => 22,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-02-12 01:00:33',
                'updated_at' => '2026-02-12 01:00:33',
            ),
            22 => 
            array (
                'id' => 23,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 3,
                'role_id' => 3,
                'user_id' => 3,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-02-16 17:48:12',
                'updated_at' => '2026-02-16 17:48:12',
            ),
            23 => 
            array (
                'id' => 24,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 2,
                'role_id' => 3,
                'user_id' => 4,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-02-16 18:29:38',
                'updated_at' => '2026-02-16 18:29:38',
            ),
            24 => 
            array (
                'id' => 25,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => NULL,
                'role_id' => 6,
                'user_id' => 23,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-05-25 18:48:34',
                'updated_at' => '2026-05-25 18:48:34',
            ),
            25 => 
            array (
                'id' => 26,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => NULL,
                'role_id' => 6,
                'user_id' => 24,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-06-15 03:27:33',
                'updated_at' => '2026-06-15 03:27:33',
            ),
            26 => 
            array (
                'id' => 27,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 4,
                'role_id' => 5,
                'user_id' => 5,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-06-15 19:06:44',
                'updated_at' => '2026-06-15 19:06:44',
            ),
            27 => 
            array (
                'id' => 28,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 1,
                'role_id' => 5,
                'user_id' => 5,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-06-15 19:06:51',
                'updated_at' => '2026-06-15 19:06:51',
            ),
            28 => 
            array (
                'id' => 29,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 1,
                'role_id' => 5,
                'user_id' => 4,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-06-18 19:23:39',
                'updated_at' => '2026-06-18 19:23:39',
            ),
            29 => 
            array (
                'id' => 30,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 3,
                'role_id' => 10,
                'user_id' => 3,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-07-07 01:44:01',
                'updated_at' => '2026-07-07 01:44:01',
            ),
            30 => 
            array (
                'id' => 31,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 4,
                'role_id' => 9,
                'user_id' => 25,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-07-29 19:59:34',
                'updated_at' => '2026-07-29 19:59:34',
            ),
            31 => 
            array (
                'id' => 32,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 3,
                'role_id' => 3,
                'user_id' => 26,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-08-14 19:00:16',
                'updated_at' => '2026-08-14 19:00:16',
            ),
            32 => 
            array (
                'id' => 33,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => NULL,
                'role_id' => 4,
                'user_id' => 27,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-08-14 19:03:48',
                'updated_at' => '2026-08-14 19:03:48',
            ),
            33 => 
            array (
                'id' => 34,
                'is_active' => 1,
                'is_primary' => 0,
                'laboratory_id' => 3,
                'role_id' => 10,
                'user_id' => 27,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-02-12 00:25:20',
                'updated_at' => '2026-02-12 00:25:20',
            ),
            34 => 
            array (
                'id' => 35,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => NULL,
                'role_id' => 6,
                'user_id' => 28,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-08-20 00:19:02',
                'updated_at' => '2026-08-20 00:19:02',
            ),
        ));


    }
}
