<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UserRolesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('user_roles')->delete();
        
        \DB::table('user_roles')->insert(array (
            0 => 
            array (
                'id' => 1,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => NULL,
                'role_id' => 1,
                'user_id' => 1,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-02-11 22:59:44',
                'updated_at' => '2026-02-11 22:59:44',
            ),
            1 => 
            array (
                'id' => 2,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => NULL,
                'role_id' => 4,
                'user_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-02-11 23:26:59',
                'updated_at' => '2026-02-11 23:26:59',
            ),
            2 => 
            array (
                'id' => 3,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => NULL,
                'role_id' => 2,
                'user_id' => 3,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-02-11 23:33:36',
                'updated_at' => '2026-02-11 23:33:36',
            ),
            3 => 
            array (
                'id' => 4,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 1,
                'role_id' => 3,
                'user_id' => 4,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-02-11 23:36:00',
                'updated_at' => '2026-02-11 23:36:00',
            ),
            4 => 
            array (
                'id' => 5,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 4,
                'role_id' => 3,
                'user_id' => 5,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-02-11 23:37:54',
                'updated_at' => '2026-02-11 23:37:54',
            ),
            5 => 
            array (
                'id' => 6,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 1,
                'role_id' => 5,
                'user_id' => 6,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-02-11 23:41:38',
                'updated_at' => '2026-02-11 23:41:38',
            ),
            6 => 
            array (
                'id' => 7,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 1,
                'role_id' => 5,
                'user_id' => 7,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-02-11 23:44:47',
                'updated_at' => '2026-02-11 23:44:47',
            ),
            7 => 
            array (
                'id' => 8,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 1,
                'role_id' => 5,
                'user_id' => 8,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-02-11 23:46:39',
                'updated_at' => '2026-02-11 23:46:39',
            ),
            8 => 
            array (
                'id' => 9,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 2,
                'role_id' => 5,
                'user_id' => 9,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-02-11 23:48:09',
                'updated_at' => '2026-02-11 23:48:09',
            ),
            9 => 
            array (
                'id' => 10,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 2,
                'role_id' => 5,
                'user_id' => 10,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-02-11 23:49:01',
                'updated_at' => '2026-02-11 23:49:01',
            ),
            10 => 
            array (
                'id' => 11,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 2,
                'role_id' => 5,
                'user_id' => 11,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-02-11 23:49:53',
                'updated_at' => '2026-02-11 23:49:53',
            ),
            11 => 
            array (
                'id' => 12,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 3,
                'role_id' => 10,
                'user_id' => 12,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-02-12 00:23:47',
                'updated_at' => '2026-02-12 00:23:47',
            ),
            12 => 
            array (
                'id' => 13,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 3,
                'role_id' => 10,
                'user_id' => 13,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-02-12 00:25:20',
                'updated_at' => '2026-02-12 00:25:20',
            ),
            13 => 
            array (
                'id' => 14,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 3,
                'role_id' => 10,
                'user_id' => 14,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-02-12 00:26:19',
                'updated_at' => '2026-02-12 00:26:19',
            ),
            14 => 
            array (
                'id' => 15,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 2,
                'role_id' => 9,
                'user_id' => 15,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-02-12 00:29:09',
                'updated_at' => '2026-02-12 00:29:09',
            ),
            15 => 
            array (
                'id' => 16,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 1,
                'role_id' => 9,
                'user_id' => 16,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-02-12 00:30:34',
                'updated_at' => '2026-02-12 00:30:34',
            ),
            16 => 
            array (
                'id' => 17,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => NULL,
                'role_id' => 8,
                'user_id' => 17,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-02-12 00:31:39',
                'updated_at' => '2026-02-12 00:31:39',
            ),
            17 => 
            array (
                'id' => 18,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 3,
                'role_id' => 9,
                'user_id' => 18,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-02-12 00:33:43',
                'updated_at' => '2026-02-12 00:33:43',
            ),
            18 => 
            array (
                'id' => 19,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => NULL,
                'role_id' => 7,
                'user_id' => 19,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-02-12 00:54:07',
                'updated_at' => '2026-02-12 00:54:07',
            ),
            19 => 
            array (
                'id' => 20,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => NULL,
                'role_id' => 6,
                'user_id' => 20,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-02-12 00:54:53',
                'updated_at' => '2026-02-12 00:54:53',
            ),
            20 => 
            array (
                'id' => 21,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => NULL,
                'role_id' => 7,
                'user_id' => 21,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-02-12 00:59:22',
                'updated_at' => '2026-02-12 00:59:22',
            ),
            21 => 
            array (
                'id' => 22,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => NULL,
                'role_id' => 6,
                'user_id' => 22,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-02-12 01:00:33',
                'updated_at' => '2026-02-12 01:00:33',
            ),
            22 => 
            array (
                'id' => 23,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 3,
                'role_id' => 3,
                'user_id' => 3,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-02-16 17:48:12',
                'updated_at' => '2026-02-16 17:48:12',
            ),
            23 => 
            array (
                'id' => 24,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 2,
                'role_id' => 3,
                'user_id' => 4,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-02-16 18:29:38',
                'updated_at' => '2026-02-16 18:29:38',
            ),
            24 => 
            array (
                'id' => 25,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => NULL,
                'role_id' => 6,
                'user_id' => 23,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-05-25 18:48:34',
                'updated_at' => '2026-05-25 18:48:34',
            ),
            25 => 
            array (
                'id' => 26,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => NULL,
                'role_id' => 2,
                'user_id' => 24,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-06-30 18:17:36',
                'updated_at' => '2026-06-30 18:17:36',
            ),
            26 => 
            array (
                'id' => 27,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 3,
                'role_id' => 3,
                'user_id' => 26,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-06-30 18:23:27',
                'updated_at' => '2026-06-30 18:23:27',
            ),
            27 => 
            array (
                'id' => 28,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 6,
                'role_id' => 3,
                'user_id' => 27,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-06-30 18:25:18',
                'updated_at' => '2026-06-30 18:25:18',
            ),
            28 => 
            array (
                'id' => 29,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 5,
                'role_id' => 3,
                'user_id' => 28,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-06-30 18:26:21',
                'updated_at' => '2026-06-30 18:26:21',
            ),
            29 => 
            array (
                'id' => 30,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 2,
                'role_id' => 3,
                'user_id' => 29,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-06-30 18:28:04',
                'updated_at' => '2026-06-30 18:28:04',
            ),
            30 => 
            array (
                'id' => 31,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => NULL,
                'role_id' => 4,
                'user_id' => 30,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-06-30 18:33:23',
                'updated_at' => '2026-06-30 18:33:23',
            ),
            31 => 
            array (
                'id' => 32,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => NULL,
                'role_id' => 8,
                'user_id' => 31,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-06-30 18:34:24',
                'updated_at' => '2026-06-30 18:34:24',
            ),
            32 => 
            array (
                'id' => 33,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 6,
                'role_id' => 5,
                'user_id' => 32,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-06-30 18:35:35',
                'updated_at' => '2026-06-30 18:35:35',
            ),
            33 => 
            array (
                'id' => 34,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 6,
                'role_id' => 5,
                'user_id' => 33,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-06-30 18:36:44',
                'updated_at' => '2026-06-30 18:36:44',
            ),
            34 => 
            array (
                'id' => 35,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 2,
                'role_id' => 5,
                'user_id' => 34,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-06-30 18:37:46',
                'updated_at' => '2026-06-30 18:37:46',
            ),
            35 => 
            array (
                'id' => 36,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 2,
                'role_id' => 5,
                'user_id' => 35,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-06-30 18:39:02',
                'updated_at' => '2026-06-30 18:39:02',
            ),
            36 => 
            array (
                'id' => 37,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 5,
                'role_id' => 5,
                'user_id' => 36,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-06-30 18:40:10',
                'updated_at' => '2026-06-30 18:40:10',
            ),
            37 => 
            array (
                'id' => 38,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 3,
                'role_id' => 10,
                'user_id' => 37,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-06-30 18:41:13',
                'updated_at' => '2026-06-30 18:41:13',
            ),
            38 => 
            array (
                'id' => 39,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 3,
                'role_id' => 10,
                'user_id' => 38,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-06-30 18:42:15',
                'updated_at' => '2026-06-30 18:42:15',
            ),
            39 => 
            array (
                'id' => 40,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 3,
                'role_id' => 10,
                'user_id' => 39,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-06-30 18:43:26',
                'updated_at' => '2026-06-30 18:43:26',
            ),
            40 => 
            array (
                'id' => 41,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => NULL,
                'role_id' => 7,
                'user_id' => 40,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-06-30 18:44:21',
                'updated_at' => '2026-06-30 18:44:21',
            ),
            41 => 
            array (
                'id' => 42,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => NULL,
                'role_id' => 6,
                'user_id' => 41,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-06-30 18:45:01',
                'updated_at' => '2026-06-30 18:45:01',
            ),
            42 => 
            array (
                'id' => 43,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => NULL,
                'role_id' => 2,
                'user_id' => 42,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-06-30 19:41:40',
                'updated_at' => '2026-06-30 19:41:40',
            ),
            43 => 
            array (
                'id' => 44,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 3,
                'role_id' => 3,
                'user_id' => 43,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-06-30 19:44:12',
                'updated_at' => '2026-06-30 19:44:12',
            ),
            44 => 
            array (
                'id' => 45,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 6,
                'role_id' => 3,
                'user_id' => 44,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-06-30 19:45:56',
                'updated_at' => '2026-06-30 19:45:56',
            ),
            45 => 
            array (
                'id' => 46,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => NULL,
                'role_id' => 4,
                'user_id' => 45,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-06-30 19:47:23',
                'updated_at' => '2026-06-30 19:47:23',
            ),
            46 => 
            array (
                'id' => 47,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 3,
                'role_id' => 10,
                'user_id' => 46,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-06-30 19:48:40',
                'updated_at' => '2026-06-30 19:48:40',
            ),
            47 => 
            array (
                'id' => 48,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 3,
                'role_id' => 10,
                'user_id' => 47,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-06-30 19:52:42',
                'updated_at' => '2026-06-30 19:52:42',
            ),
            48 => 
            array (
                'id' => 49,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 3,
                'role_id' => 10,
                'user_id' => 48,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-06-30 21:46:32',
                'updated_at' => '2026-06-30 21:46:32',
            ),
            49 => 
            array (
                'id' => 50,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 3,
                'role_id' => 10,
                'user_id' => 49,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-06-30 21:47:45',
                'updated_at' => '2026-06-30 21:47:45',
            ),
            50 => 
            array (
                'id' => 51,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 3,
                'role_id' => 10,
                'user_id' => 50,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-06-30 21:49:22',
                'updated_at' => '2026-06-30 21:49:22',
            ),
            51 => 
            array (
                'id' => 52,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 3,
                'role_id' => 10,
                'user_id' => 51,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-06-30 21:50:48',
                'updated_at' => '2026-06-30 21:50:48',
            ),
            52 => 
            array (
                'id' => 53,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 3,
                'role_id' => 10,
                'user_id' => 52,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-06-30 21:51:49',
                'updated_at' => '2026-06-30 21:51:49',
            ),
            53 => 
            array (
                'id' => 54,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 2,
                'role_id' => 5,
                'user_id' => 53,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-06-30 21:52:55',
                'updated_at' => '2026-06-30 21:52:55',
            ),
            54 => 
            array (
                'id' => 55,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 2,
                'role_id' => 5,
                'user_id' => 54,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-06-30 21:54:08',
                'updated_at' => '2026-06-30 21:54:08',
            ),
            55 => 
            array (
                'id' => 56,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 2,
                'role_id' => 5,
                'user_id' => 55,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-06-30 21:55:04',
                'updated_at' => '2026-06-30 21:55:04',
            ),
            56 => 
            array (
                'id' => 57,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 6,
                'role_id' => 5,
                'user_id' => 56,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-06-30 21:57:22',
                'updated_at' => '2026-06-30 21:57:22',
            ),
            57 => 
            array (
                'id' => 58,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 6,
                'role_id' => 5,
                'user_id' => 57,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-06-30 21:58:20',
                'updated_at' => '2026-06-30 21:58:20',
            ),
            58 => 
            array (
                'id' => 59,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 3,
                'role_id' => 10,
                'user_id' => 58,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-06-30 21:59:16',
                'updated_at' => '2026-06-30 21:59:16',
            ),
            59 => 
            array (
                'id' => 60,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => NULL,
                'role_id' => 4,
                'user_id' => 59,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-06-30 22:51:41',
                'updated_at' => '2026-06-30 22:51:41',
            ),
            60 => 
            array (
                'id' => 61,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => NULL,
                'role_id' => 2,
                'user_id' => 60,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-06-30 22:55:53',
                'updated_at' => '2026-06-30 22:55:53',
            ),
            61 => 
            array (
                'id' => 62,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 3,
                'role_id' => 3,
                'user_id' => 61,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-06-30 22:57:06',
                'updated_at' => '2026-06-30 22:57:06',
            ),
            62 => 
            array (
                'id' => 63,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 2,
                'role_id' => 3,
                'user_id' => 62,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-06-30 23:04:28',
                'updated_at' => '2026-06-30 23:04:28',
            ),
            63 => 
            array (
                'id' => 64,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 1,
                'role_id' => 3,
                'user_id' => 63,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-06-30 23:08:48',
                'updated_at' => '2026-06-30 23:08:48',
            ),
            64 => 
            array (
                'id' => 65,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 3,
                'role_id' => 10,
                'user_id' => 64,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-06-30 23:12:08',
                'updated_at' => '2026-06-30 23:12:08',
            ),
            65 => 
            array (
                'id' => 66,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 3,
                'role_id' => 10,
                'user_id' => 65,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-06-30 23:12:50',
                'updated_at' => '2026-06-30 23:12:50',
            ),
            66 => 
            array (
                'id' => 67,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => NULL,
                'role_id' => 4,
                'user_id' => 66,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-06-30 23:20:42',
                'updated_at' => '2026-06-30 23:20:42',
            ),
            67 => 
            array (
                'id' => 68,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => NULL,
                'role_id' => 4,
                'user_id' => 67,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-06-30 23:24:02',
                'updated_at' => '2026-06-30 23:24:02',
            ),
            68 => 
            array (
                'id' => 69,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => NULL,
                'role_id' => 4,
                'user_id' => 68,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-06-30 23:27:19',
                'updated_at' => '2026-06-30 23:27:19',
            ),
            69 => 
            array (
                'id' => 70,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => NULL,
                'role_id' => 6,
                'user_id' => 69,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-06-30 23:29:26',
                'updated_at' => '2026-06-30 23:29:26',
            ),
            70 => 
            array (
                'id' => 71,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => NULL,
                'role_id' => 7,
                'user_id' => 70,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-06-30 23:30:06',
                'updated_at' => '2026-06-30 23:30:06',
            ),
            71 => 
            array (
                'id' => 72,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => NULL,
                'role_id' => 6,
                'user_id' => 71,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-06-30 23:36:42',
                'updated_at' => '2026-06-30 23:36:42',
            ),
            72 => 
            array (
                'id' => 73,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => NULL,
                'role_id' => 4,
                'user_id' => 72,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-06-30 23:40:28',
                'updated_at' => '2026-06-30 23:40:28',
            ),
            73 => 
            array (
                'id' => 74,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => NULL,
                'role_id' => 2,
                'user_id' => 73,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-06-30 23:55:15',
                'updated_at' => '2026-06-30 23:55:15',
            ),
            74 => 
            array (
                'id' => 75,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 3,
                'role_id' => 3,
                'user_id' => 74,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-06-30 23:57:56',
                'updated_at' => '2026-06-30 23:57:56',
            ),
            75 => 
            array (
                'id' => 76,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 3,
                'role_id' => 10,
                'user_id' => 75,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-06-30 23:59:26',
                'updated_at' => '2026-06-30 23:59:26',
            ),
            76 => 
            array (
                'id' => 77,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 3,
                'role_id' => 10,
                'user_id' => 76,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-07-01 00:00:37',
                'updated_at' => '2026-07-01 00:00:37',
            ),
            77 => 
            array (
                'id' => 78,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 3,
                'role_id' => 10,
                'user_id' => 77,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-07-01 00:01:26',
                'updated_at' => '2026-07-01 00:01:26',
            ),
            78 => 
            array (
                'id' => 79,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 3,
                'role_id' => 10,
                'user_id' => 78,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-07-01 00:02:44',
                'updated_at' => '2026-07-01 00:02:44',
            ),
            79 => 
            array (
                'id' => 80,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 3,
                'role_id' => 10,
                'user_id' => 79,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-07-01 00:03:40',
                'updated_at' => '2026-07-01 00:03:40',
            ),
            80 => 
            array (
                'id' => 81,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 1,
                'role_id' => 3,
                'user_id' => 80,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-07-01 00:04:56',
                'updated_at' => '2026-07-01 00:04:56',
            ),
            81 => 
            array (
                'id' => 82,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 7,
                'role_id' => 3,
                'user_id' => 81,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-07-01 00:07:39',
                'updated_at' => '2026-07-01 00:07:39',
            ),
            82 => 
            array (
                'id' => 83,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 1,
                'role_id' => 5,
                'user_id' => 82,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-07-01 00:11:30',
                'updated_at' => '2026-07-01 00:11:30',
            ),
            83 => 
            array (
                'id' => 84,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 2,
                'role_id' => 3,
                'user_id' => 83,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-07-01 00:15:13',
                'updated_at' => '2026-07-01 00:15:13',
            ),
            84 => 
            array (
                'id' => 85,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 2,
                'role_id' => 5,
                'user_id' => 84,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-07-01 00:52:18',
                'updated_at' => '2026-07-01 00:52:18',
            ),
            85 => 
            array (
                'id' => 86,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 2,
                'role_id' => 5,
                'user_id' => 85,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-07-01 00:53:12',
                'updated_at' => '2026-07-01 00:53:12',
            ),
            86 => 
            array (
                'id' => 87,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 9,
                'role_id' => 5,
                'user_id' => 86,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-07-01 00:55:24',
                'updated_at' => '2026-07-01 00:55:24',
            ),
            87 => 
            array (
                'id' => 88,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 9,
                'role_id' => 5,
                'user_id' => 87,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-07-01 00:56:15',
                'updated_at' => '2026-07-01 00:56:15',
            ),
            88 => 
            array (
                'id' => 89,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 7,
                'role_id' => 5,
                'user_id' => 88,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-07-01 00:57:34',
                'updated_at' => '2026-07-01 00:57:34',
            ),
            89 => 
            array (
                'id' => 90,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 7,
                'role_id' => 5,
                'user_id' => 89,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-07-01 00:58:21',
                'updated_at' => '2026-07-01 00:58:21',
            ),
            90 => 
            array (
                'id' => 91,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 1,
                'role_id' => 5,
                'user_id' => 90,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-07-01 00:59:09',
                'updated_at' => '2026-07-01 00:59:09',
            ),
            91 => 
            array (
                'id' => 92,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => NULL,
                'role_id' => 4,
                'user_id' => 91,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-07-01 01:01:30',
                'updated_at' => '2026-07-01 01:01:30',
            ),
            92 => 
            array (
                'id' => 93,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => NULL,
                'role_id' => 4,
                'user_id' => 92,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-07-01 01:02:16',
                'updated_at' => '2026-07-01 01:02:16',
            ),
            93 => 
            array (
                'id' => 94,
                'is_active' => 1,
                'is_primary' => 1,
                'laboratory_id' => 9,
                'role_id' => 3,
                'user_id' => 93,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-07-01 01:03:11',
                'updated_at' => '2026-07-01 01:03:11',
            ),
        ));
        
        
    }
}